# Generated by Django 3.2.2 on 2021-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tags',
            field=models.ManyToManyField(null=True, to='products.Tag'),
        ),
    ]
