# Generated by Django 3.2.2 on 2021-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_items_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Agricultural Tools', 'Agricultural Tools'), ('Fodder', 'Fodder'), ('Dairy products', 'Dairy Products')], max_length=200, null=True),
        ),
    ]
